GET http://localhost:3000/
###
GET http://localhost:3000/users
###
GET http://localhost:3000/users/6825f0f2ee3909e63153bce9
###
GET http://localhost:3000/users/6825f141ee3909e63153bcea
###
GET http://localhost:3000/users/6825f165ee3909e63153bceb
###
GET https://cse341-project1-knyc.onrender.com
###
GET https://cse341-project1-knyc.onrender.com/users


### // The following request will CREATE a new user in the database
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Ernie Ritz",
    "lastName": "Balacano",
    "email": "kariza@gmail.com",
    "favoriteColor": "red",
    "birthday": "1999-06-28"
}

### // The following request will UPDATE a user in the database
PUT http://localhost:3000/users/6825f0f2ee3909e63153bce9 HTTP/1.1
content-type: application/json

{
    "firstName": "Cav",
    "lastName": "Gaylon",
    "email": "cav@gmail.com",
    "favoriteColor": "mink",
    "birthday": "1999-06-28"
}
### // The following request will DELETE a user in the database
DELETE http://localhost:3000/users/682c934d60c010b6b37eb0a1 HTTP/1.1

